name: covid_detective
description: Check XRay for Covid

publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.6
  image_cropper: ^3.0.1
  animated_splash_screen: ^1.3.0
  page_transition: ^2.0.9
  injectable: ^2.1.0
  intl: ^0.18.0
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  dartz: ^0.10.1
  dio: ^5.0.3
  http_parser: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  injectable_generator: ^2.1.4
  build_runner: ^2.3.3
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf